# Cloud Build configuration for Elena Construction Agent
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/elena-agent:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/elena-agent:latest'
      - '.'
    timeout: 1200s

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/elena-agent:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/elena-agent:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'elena-agent'
      - '--image=gcr.io/$PROJECT_ID/elena-agent:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300'
      - '--max-instances=10'
      - '--min-instances=1'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID,ALLOW_PRODUCTION_FIRESTORE=true,PINECONE_ENVIRONMENT=us-east-1'
      - '--set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest,PINECONE_API_KEY=PINECONE_API_KEY:latest'

timeout: 1800s

images:
  - 'gcr.io/$PROJECT_ID/elena-agent:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/elena-agent:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
